(in-package #:bible-translations)

(defparameter *pentateuch*
  '(("Gn"  50 "1. Mojžíšova")
    ("Ex" 40 "2. Mojžíšova")
    ("Lv" 27 "3. Mojžíšova")
    ("Nu" 36 "4. Mojžíšova")
    ("Dt" 34 "5. Mojžíšova")))

(defparameter *hebrew-scriptures*
  (append *pentateuch*
          '(("Joz" 24 "Jozue")
            ("Sd" 21 "Soudci")
            ("Rt" 4 "Rut")
            ("1S" 31 "1. Samuelova")
            ("2S" 24 "2. Samuelova")
            ("1Kr" 22 "1. Královská")
            ("2Kr" 25 "2. Královská")
            ("1Pa" 29 "1. Paralipomenon")
            ("2Pa" 36 "2. Paralipomenon")
            ("Ezd" 10 "Ezra")
            ("Neh" 13 "Nehemjáš")
            ("Est" 10 "Ester")
            ("Jb" 42 "Job")
            ("Z" 150 "Žalmy")
            ("Pr" 31 "Přísloví")
            ("Kaz" 12 "Kazatel")
            ("Pis" 8 "Šalomounova píseň")
            ("Iz" 66 "Izajáš")
            ("Jr" 52 "Jeremjáš")
            ("Pl" 22 "Nářky")
            ("Ez" 48 "Ezekiel")
            ("Da" 12 "Daniel")
            ("Oz" 14 "Ozeáš")
            ("Jl" 20 "Joel")
            ("Am" 9 "Amos")
            ("Abd" 21 "Obadjáš")
            ("Jon" 4 "Jonáš")
            ("Mi" 7 "Micheáš")
            ("Na" 3 "Nahum")
            ("Abk" 3 "Habakuk")
            ("Sf" 3 "Sefanjáš")
            ("Ag" 2 "Ageus")
            ("Za" 14 "Zecharjáš")
            ("Mal" 4 "Malachiáš"))))

(defparameter *greek-scriptures*
  '(("Mt" 28 "Matouš")
    ("Mk" 16 "Marek")
    ("L" 24 "Lukáš")
    ("J" 21 "Jan")
    ("Sk" 28 "Skutky apoštolů")
    ("R" 16 "Římanům")
    ("1K" 16 "1. Korinťanům")
    ("2K" 13 "2. Korinťanům")
    ("Ga" 6 "Galaťanům")
    ("Ef" 6 "Efezanům")
    ("Fp" 4 "Filipanům")
    ("Ko" 4 "Kolosanům")
    ("1Te" 5 "1. Tesaloničanům")
    ("2Te" 3 "2. Tesaloničanům")
    ("1Tm" 6 "1. Timoteovi")
    ("2Tm" 4 "2. Timoteovi")
    ("Tit" 3 "Titovi")
    ("Fm" 1 "Filemonovi")
    ("Zd" 13 "Hebrejcům")
    ("Jk" 5 "Jakub")
    ("1P" 5 "1. Petra")
    ("2P" 3 "2. Petra")
    ("1J" 5 "1. Jana")
    ("2J" 1 "2. Jana")
    ("3J" 1 "3. Jana")
    ("Ju" 1 "Juda")
    ("Zj" 22 "Zjevení")))

(defparameter *canonical-books*
  (append *hebrew-scriptures* *greek-scriptures*))

(defparameter *apocrypha*
  '(("Tob" 14 "Tóbijáš")
    ("Jud" 16 "Júdit")
    ("Mou" 19 "Kniha moudrosti")
    ("Sir" 51 "Sírachovec")
    ("Bar" 6 "Báruk")
    ("1Ma" 16 "1. Makabejská")
    ("2Ma" 15 "2. Makabejská")
    ("Zuz" 1 "Zuzana")
    ("Bel" 1 "Bél a drak")))

(defparameter *hebrew-catholic-books*
  (append *hebrew-scriptures* *apocrypha*))

(defparameter *catholic-books*
  (append *canonical-books* *apocrypha*))

(defparameter *translations* `(("CSP" ,*canonical-books*  "Czech Study Bible Translation (CZ)")
                               ("PMP" ,*greek-scriptures* "Miloš Pavlík Translation - NT (CZ)")
                               ("ZP"  ,*greek-scriptures* "František Žilka Translation - NT (CZ)")
                               ("OP"  ,*greek-scriptures* "Ondřej M. Petrů Translation - NT (CZ)")
                               ("CRP" ,*pentateuch*       "Czech Rabbinical Translation (Pentateuch - CZ)")
                               ("BKR1" ,*canonical-books* "Bible of Kralice (CZ - 1579)")
                               ("BKR" ,*canonical-books*  "Bible of Kralice (CZ - 1613)")
                               ("NBK98" ,*greek-scriptures* "New Bible of Kralice (CZ) (1998 - only NT)")
                               ("NBK" ,*greek-scriptures* "New Bible of Kralice (CZ) (2002 - only NT)")
                               ("NBK06" ,*greek-scriptures* "New Bible of Kralice (CZ) (2006)")
                               ("B21" ,*canonical-books*  "Bible 21 (CZ)")
                               ("PNS" ,*canonical-books*  "New World Translation of the Holy Scriptures")
                               ("NK"  ,*greek-scriptures* "New Covenant")
                               ("COL" ,*greek-scriptures* "New Testament - Dr. Rudolf Col (1947)")
                               ("HEJCL" ,*hebrew-catholic-books* "Dr. Jan Hejčl (1930) - Old Testament and Deuterocanonical books")
                               ("ROH" ,*canonical-books*  "Jozef Roháček Translation - Autorized Version Dušan Seberíni (SK)")
                               ;("SKP" ,*catholic-books*   "Slovak Catholic translation")
                               ("SEP" ,*catholic-books*  "Slovak ecumenical translation (2008)")
                               ("SEVP" ,*canonical-books* "Slovak Evangelical translation")))
